/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zm.client.jni;

public class ChangeSet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ChangeSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChangeSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javaZmJNI.delete_ChangeSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChangeSet() {
    this(javaZmJNI.new_ChangeSet__SWIG_0(), true);
  }

  public ChangeSet(String journalFileName) {
    this(javaZmJNI.new_ChangeSet__SWIG_1(journalFileName), true);
  }

  public boolean write(String journalFileName) {
    return javaZmJNI.ChangeSet_write(swigCPtr, this, journalFileName);
  }

  public SWIGTYPE_p_std__listT_boost__shared_ptrT_zm__JournalItem_t_t getJournal() {
    return new SWIGTYPE_p_std__listT_boost__shared_ptrT_zm__JournalItem_t_t(javaZmJNI.ChangeSet_getJournal(swigCPtr, this), false);
  }

  public void add_remove_entry(String node_uid) {
    javaZmJNI.ChangeSet_add_remove_entry(swigCPtr, this, node_uid);
  }

  public void append(SWIGTYPE_p_std__listT_boost__shared_ptrT_zm__JournalItem_t_t changes) {
    javaZmJNI.ChangeSet_append(swigCPtr, this, SWIGTYPE_p_std__listT_boost__shared_ptrT_zm__JournalItem_t_t.getCPtr(changes));
  }

  public void clear() {
    javaZmJNI.ChangeSet_clear(swigCPtr, this);
  }

  public boolean isEmpty() {
    return javaZmJNI.ChangeSet_isEmpty(swigCPtr, this);
  }

  public long size() {
    return javaZmJNI.ChangeSet_size(swigCPtr, this);
  }

  public void debug_dump() {
    javaZmJNI.ChangeSet_debug_dump(swigCPtr, this);
  }

}
