/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zm.client.jni;

public class JournalItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected JournalItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JournalItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javaZmJNI.delete_JournalItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t createCreate(String item_uid, String caption) {
    return new SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t(javaZmJNI.JournalItem_createCreate(item_uid, caption), true);
  }

  public static SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t createSetStringValue(String item_uid, String name, String value) {
    return new SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t(javaZmJNI.JournalItem_createSetStringValue(item_uid, name, value), true);
  }

  public static SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t createErase(String item_uid) {
    return new SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t(javaZmJNI.JournalItem_createErase(item_uid), true);
  }

  public static SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t createAddAttribute(String Uid, String name) {
    return new SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t(javaZmJNI.JournalItem_createAddAttribute(Uid, name), true);
  }

  public static SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t createChangeCaption(String item_uid, String value) {
    return new SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t(javaZmJNI.JournalItem_createChangeCaption(item_uid, value), true);
  }

  public static SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t createConnect(String item_uid, SWIGTYPE_p_std__pairT_std__string_int_t other_item_uid) {
    return new SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t(javaZmJNI.JournalItem_createConnect(item_uid, SWIGTYPE_p_std__pairT_std__string_int_t.getCPtr(other_item_uid)), true);
  }

  public static SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t createDisconnect(String item_uid, String other_item_uid) {
    return new SWIGTYPE_p_boost__shared_ptrT_zm__JournalItem_t(javaZmJNI.JournalItem_createDisconnect(item_uid, other_item_uid), true);
  }

  public void setItem_uid(String value) {
    javaZmJNI.JournalItem_item_uid_set(swigCPtr, this, value);
  }

  public String getItem_uid() {
    return javaZmJNI.JournalItem_item_uid_get(swigCPtr, this);
  }

  public void setType(JournalItem.ChangeType value) {
    javaZmJNI.JournalItem_type_set(swigCPtr, this, value.swigValue());
  }

  public JournalItem.ChangeType getType() {
    return JournalItem.ChangeType.swigToEnum(javaZmJNI.JournalItem_type_get(swigCPtr, this));
  }

  public void setTime(String value) {
    javaZmJNI.JournalItem_time_set(swigCPtr, this, value);
  }

  public String getTime() {
    return javaZmJNI.JournalItem_time_get(swigCPtr, this);
  }

  public void setKey(String value) {
    javaZmJNI.JournalItem_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return javaZmJNI.JournalItem_key_get(swigCPtr, this);
  }

  public void setValue(String value) {
    javaZmJNI.JournalItem_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return javaZmJNI.JournalItem_value_get(swigCPtr, this);
  }

  public final static class ChangeType {
    public final static JournalItem.ChangeType CreateItem = new JournalItem.ChangeType("CreateItem");
    public final static JournalItem.ChangeType EraseItem = new JournalItem.ChangeType("EraseItem");
    public final static JournalItem.ChangeType SetStringValue = new JournalItem.ChangeType("SetStringValue");
    public final static JournalItem.ChangeType AddAttribute = new JournalItem.ChangeType("AddAttribute");
    public final static JournalItem.ChangeType ChangeCaption = new JournalItem.ChangeType("ChangeCaption");
    public final static JournalItem.ChangeType Connect = new JournalItem.ChangeType("Connect");
    public final static JournalItem.ChangeType Disconnect = new JournalItem.ChangeType("Disconnect");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ChangeType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ChangeType.class + " with value " + swigValue);
    }

    private ChangeType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ChangeType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ChangeType(String swigName, ChangeType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ChangeType[] swigValues = { CreateItem, EraseItem, SetStringValue, AddAttribute, ChangeCaption, Connect, Disconnect };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
