/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zm.client.jni;

public class zmGtdModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zmGtdModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zmGtdModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        javaZmJNI.delete_zmGtdModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public zmGtdModel() {
    this(javaZmJNI.new_zmGtdModel__SWIG_0(), true);
  }

  public zmGtdModel(MindMatterModel model) {
    this(javaZmJNI.new_zmGtdModel__SWIG_1(MindMatterModel.getCPtr(model), model), true);
  }

  public void disableHashChecking() {
    javaZmJNI.zmGtdModel_disableHashChecking(swigCPtr, this);
  }

  public void setTraceLevel(int level) {
    javaZmJNI.zmGtdModel_setTraceLevel(swigCPtr, this, level);
  }

  public boolean hasUsedUsername() {
    return javaZmJNI.zmGtdModel_hasUsedUsername(swigCPtr, this);
  }

  public boolean hasUsedHostname() {
    return javaZmJNI.zmGtdModel_hasUsedHostname(swigCPtr, this);
  }

  public void setUsedUsername(String username) {
    javaZmJNI.zmGtdModel_setUsedUsername(swigCPtr, this, username);
  }

  public void setUsedHostname(String hostname) {
    javaZmJNI.zmGtdModel_setUsedHostname(swigCPtr, this, hostname);
  }

  public void setConfigPersistance(boolean value) {
    javaZmJNI.zmGtdModel_setConfigPersistance(swigCPtr, this, value);
  }

  public void setLocalFolder(String path) {
    javaZmJNI.zmGtdModel_setLocalFolder(swigCPtr, this, path);
  }

  public void addDomainSyncFolder(String domainName, String path) {
    javaZmJNI.zmGtdModel_addDomainSyncFolder(swigCPtr, this, domainName, path);
  }

  public void initialize() {
    javaZmJNI.zmGtdModel_initialize(swigCPtr, this);
  }

  public void sync() {
    javaZmJNI.zmGtdModel_sync(swigCPtr, this);
  }

  public void createSnapshot() {
    javaZmJNI.zmGtdModel_createSnapshot(swigCPtr, this);
  }

  public void localSave(String filename) {
    javaZmJNI.zmGtdModel_localSave__SWIG_0(swigCPtr, this, filename);
  }

  public void localSave() {
    javaZmJNI.zmGtdModel_localSave__SWIG_1(swigCPtr, this);
  }

  public long getItemCount() {
    return javaZmJNI.zmGtdModel_getItemCount(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getItems() {
    return new SWIGTYPE_p_std__vectorT_std__string_t(javaZmJNI.zmGtdModel_getItems(swigCPtr, this), true);
  }

  public String getNote(String uid) {
    return javaZmJNI.zmGtdModel_getNote(swigCPtr, this, uid);
  }

  public int getImportance(String uid) {
    return javaZmJNI.zmGtdModel_getImportance(swigCPtr, this, uid);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getInboxItems(boolean includeDoneItems) {
    return new SWIGTYPE_p_std__vectorT_std__string_t(javaZmJNI.zmGtdModel_getInboxItems(swigCPtr, this, includeDoneItems), true);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getTaskItems(boolean includeStandaloneTasks, boolean includeDoneItems) {
    return new SWIGTYPE_p_std__vectorT_std__string_t(javaZmJNI.zmGtdModel_getTaskItems(swigCPtr, this, includeStandaloneTasks, includeDoneItems), true);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getProjectItems(boolean includeStandaloneTasks, boolean includeDoneItems) {
    return new SWIGTYPE_p_std__vectorT_std__string_t(javaZmJNI.zmGtdModel_getProjectItems(swigCPtr, this, includeStandaloneTasks, includeDoneItems), true);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getDoneItems() {
    return new SWIGTYPE_p_std__vectorT_std__string_t(javaZmJNI.zmGtdModel_getDoneItems(swigCPtr, this), true);
  }

  public boolean isTaskItem(String item, boolean includeStandaloneTasks) {
    return javaZmJNI.zmGtdModel_isTaskItem(swigCPtr, this, item, includeStandaloneTasks);
  }

  public boolean isInboxItem(String item) {
    return javaZmJNI.zmGtdModel_isInboxItem(swigCPtr, this, item);
  }

  public boolean isProjectItem(String item, boolean includeStandaloneTasks) {
    return javaZmJNI.zmGtdModel_isProjectItem(swigCPtr, this, item, includeStandaloneTasks);
  }

  public boolean isDone(String task_item) {
    return javaZmJNI.zmGtdModel_isDone(swigCPtr, this, task_item);
  }

  public String getParentProject(String task_item) {
    return javaZmJNI.zmGtdModel_getParentProject(swigCPtr, this, task_item);
  }

  public String getNextTask(String task_item) {
    return javaZmJNI.zmGtdModel_getNextTask(swigCPtr, this, task_item);
  }

  public String orderATask() {
    return javaZmJNI.zmGtdModel_orderATask(swigCPtr, this);
  }

  public boolean itemContentMatchesString(String uid, String searchString) {
    return javaZmJNI.zmGtdModel_itemContentMatchesString(swigCPtr, this, uid, searchString);
  }

  public void print_statistics() {
    javaZmJNI.zmGtdModel_print_statistics(swigCPtr, this);
  }

  public boolean empty() {
    return javaZmJNI.zmGtdModel_empty(swigCPtr, this);
  }

  public String createNewInboxItem(String caption) {
    return javaZmJNI.zmGtdModel_createNewInboxItem(swigCPtr, this, caption);
  }

  public void setNote(String uid, String value) {
    javaZmJNI.zmGtdModel_setNote(swigCPtr, this, uid, value);
  }

  public void plusOne(String uid) {
    javaZmJNI.zmGtdModel_plusOne(swigCPtr, this, uid);
  }

  public void registerItemAsTask(String task_item, String project_item) {
    javaZmJNI.zmGtdModel_registerItemAsTask(swigCPtr, this, task_item, project_item);
  }

  public void setDone(String task_item) {
    javaZmJNI.zmGtdModel_setDone(swigCPtr, this, task_item);
  }

  public void castToProject(String item) {
    javaZmJNI.zmGtdModel_castToProject(swigCPtr, this, item);
  }

  public void setNextTask(String project_item, String task_item) {
    javaZmJNI.zmGtdModel_setNextTask(swigCPtr, this, project_item, task_item);
  }

  public String createProject(String project_name) {
    return javaZmJNI.zmGtdModel_createProject(swigCPtr, this, project_name);
  }

  public SWIGTYPE_p_std__time_t getCreationTime(String uid) {
    return new SWIGTYPE_p_std__time_t(javaZmJNI.zmGtdModel_getCreationTime(swigCPtr, this, uid), true);
  }

  public String getCaption(String uid) {
    return javaZmJNI.zmGtdModel_getCaption(swigCPtr, this, uid);
  }

  public void setCaption(String uid, String caption) {
    javaZmJNI.zmGtdModel_setCaption(swigCPtr, this, uid, caption);
  }

  public void eraseItem(String uid) {
    javaZmJNI.zmGtdModel_eraseItem(swigCPtr, this, uid);
  }

}
